name: Windows .Net 472 (x86, x64)
on:
  push:
    #branches: [ dev ] # should just build the release when pull request is completed
    tags:
        - "dev*"    
jobs:
  release:
    name: Develop
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86, x64] 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code     

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore PinGod.VP.sln
 
    - name: Build
      shell: bash
      id: build
      run: |
        release_name="PinGod.VP-${{ matrix.target }}-${{github.ref_name}}"
        # msbuild
        msbuild.exe PinGod.VP.sln -p:Configuration=Release -p:DeployOnBuild=true -p:Platform=${{ matrix.target }} -p:OutputPath="./${release_name}/"  
        7z a -tzip "${release_name}.zip" "D:/a/pingod-controller-com/pingod-controller-com/PinGod.VP/${release_name}/*"
        7z a -tzip "${release_name}.zip" "D:/a/pingod-controller-com/pingod-controller-com/PinGod.VP.WPF/${release_name}/*"        
        # Only need this for multiple platform
        # rm -r "$release_name"  
    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true # need this so it doesn't fail after uploading the first artifact
        generateReleaseNotes: false       
        tag: ${{ github.ref_name }}
        artifacts: PinGod.VP-${{ matrix.target }}-${{github.ref_name}}.zip